package ps.emperor.easy_water.greendao;


import android.database.sqlite.SQLiteDatabase;


import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig irrigationDaoConfig;
    private final DaoConfig waterDaoConfig;
    private final DaoConfig irrigationProjectDaoConfig;
    private final DaoConfig irrigationGroupDaoConfig;
    private final DaoConfig singleValueDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig irrigationIsFirstDaoConfig;

    private final IrrigationDao irrigationDao;
    private final WaterDao waterDao;
    private final IrrigationProjectDao irrigationProjectDao;
    private final IrrigationGroupDao irrigationGroupDao;
    private final SingleValueDao singleValueDao;
    private final CustomerDao customerDao;
    private final OrderDao orderDao;
    private final IrrigationIsFirstDao irrigationIsFirstDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        irrigationDaoConfig = daoConfigMap.get(IrrigationDao.class).clone();
        irrigationDaoConfig.initIdentityScope(type);

        waterDaoConfig = daoConfigMap.get(WaterDao.class).clone();
        waterDaoConfig.initIdentityScope(type);

        irrigationProjectDaoConfig = daoConfigMap.get(IrrigationProjectDao.class).clone();
        irrigationProjectDaoConfig.initIdentityScope(type);

        irrigationGroupDaoConfig = daoConfigMap.get(IrrigationGroupDao.class).clone();
        irrigationGroupDaoConfig.initIdentityScope(type);

        singleValueDaoConfig = daoConfigMap.get(SingleValueDao.class).clone();
        singleValueDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        irrigationIsFirstDaoConfig = daoConfigMap.get(IrrigationIsFirstDao.class).clone();
        irrigationIsFirstDaoConfig.initIdentityScope(type);

        irrigationDao = new IrrigationDao(irrigationDaoConfig, this);
        waterDao = new WaterDao(waterDaoConfig, this);
        irrigationProjectDao = new IrrigationProjectDao(irrigationProjectDaoConfig, this);
        irrigationGroupDao = new IrrigationGroupDao(irrigationGroupDaoConfig, this);
        singleValueDao = new SingleValueDao(singleValueDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        irrigationIsFirstDao = new IrrigationIsFirstDao(irrigationIsFirstDaoConfig, this);

        registerDao(Irrigation.class, irrigationDao);
        registerDao(Water.class, waterDao);
        registerDao(IrrigationProject.class, irrigationProjectDao);
        registerDao(IrrigationGroup.class, irrigationGroupDao);
        registerDao(SingleValue.class, singleValueDao);
        registerDao(Customer.class, customerDao);
        registerDao(Order.class, orderDao);
        registerDao(IrrigationIsFirst.class, irrigationIsFirstDao);
    }
    
    public void clear() {
        irrigationDaoConfig.getIdentityScope().clear();
        waterDaoConfig.getIdentityScope().clear();
        irrigationProjectDaoConfig.getIdentityScope().clear();
        irrigationGroupDaoConfig.getIdentityScope().clear();
        singleValueDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        irrigationIsFirstDaoConfig.getIdentityScope().clear();
    }

    public IrrigationDao getIrrigationDao() {
        return irrigationDao;
    }

    public WaterDao getWaterDao() {
        return waterDao;
    }

    public IrrigationProjectDao getIrrigationProjectDao() {
        return irrigationProjectDao;
    }

    public IrrigationGroupDao getIrrigationGroupDao() {
        return irrigationGroupDao;
    }

    public SingleValueDao getSingleValueDao() {
        return singleValueDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public IrrigationIsFirstDao getIrrigationIsFirstDao() {
        return irrigationIsFirstDao;
    }

}
