package ps.emperor.easy_water.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IRRIGATION_IS_FIRST.
 */
public class IrrigationIsFirst {

    private Long id;
    private String irrigation;
    private Integer isFirst;

    public IrrigationIsFirst() {
    }

    public IrrigationIsFirst(Long id) {
        this.id = id;
    }

    public IrrigationIsFirst(Long id, String irrigation, Integer isFirst) {
        this.id = id;
        this.irrigation = irrigation;
        this.isFirst = isFirst;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIrrigation() {
        return irrigation;
    }

    public void setIrrigation(String irrigation) {
        this.irrigation = irrigation;
    }

    public Integer getIsFirst() {
        return isFirst;
    }

    public void setIsFirst(Integer isFirst) {
        this.isFirst = isFirst;
    }

}
