package ps.emperor.easy_water.greendao;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IRRIGATION_GROUP.
 */
public class IrrigationGroup {

    private Long id;
    private String irrigation;
    private String matchedvalue;
    private Integer matchedNum;

    public IrrigationGroup() {
    }

    public IrrigationGroup(Long id) {
        this.id = id;
    }

    public IrrigationGroup(Long id, String irrigation, String matchedvalue, Integer matchedNum) {
        this.id = id;
        this.irrigation = irrigation;
        this.matchedvalue = matchedvalue;
        this.matchedNum = matchedNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIrrigation() {
        return irrigation;
    }

    public void setIrrigation(String irrigation) {
        this.irrigation = irrigation;
    }

    public String getMatchedvalue() {
        return matchedvalue;
    }

    public void setMatchedvalue(String matchedvalue) {
        this.matchedvalue = matchedvalue;
    }

    public Integer getMatchedNum() {
        return matchedNum;
    }

    public void setMatchedNum(Integer matchedNum) {
        this.matchedNum = matchedNum;
    }

}
