package ps.emperor.easy_water.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IRRIGATION.
 */
public class Irrigation {

    private Long id;
    private String irrigation;
    private Integer isrelevance;
    private String groupnumber;
    private String valuenumber;
    private String filter;
    private String timestart;
    private String timeend;
    private String userinfo;
    private Boolean userphone;
    private Long cropsinfo;
    private String cropstime;

    public Irrigation() {
    }

    public Irrigation(Long id) {
        this.id = id;
    }

    public Irrigation(Long id, String irrigation, Integer isrelevance, String groupnumber, String valuenumber, String filter, String timestart, String timeend, String userinfo, Boolean userphone, Long cropsinfo, String cropstime) {
        this.id = id;
        this.irrigation = irrigation;
        this.isrelevance = isrelevance;
        this.groupnumber = groupnumber;
        this.valuenumber = valuenumber;
        this.filter = filter;
        this.timestart = timestart;
        this.timeend = timeend;
        this.userinfo = userinfo;
        this.userphone = userphone;
        this.cropsinfo = cropsinfo;
        this.cropstime = cropstime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIrrigation() {
        return irrigation;
    }

    public void setIrrigation(String irrigation) {
        this.irrigation = irrigation;
    }

    public Integer getIsrelevance() {
        return isrelevance;
    }

    public void setIsrelevance(Integer isrelevance) {
        this.isrelevance = isrelevance;
    }

    public String getGroupnumber() {
        return groupnumber;
    }

    public void setGroupnumber(String groupnumber) {
        this.groupnumber = groupnumber;
    }

    public String getValuenumber() {
        return valuenumber;
    }

    public void setValuenumber(String valuenumber) {
        this.valuenumber = valuenumber;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }

    public String getTimestart() {
        return timestart;
    }

    public void setTimestart(String timestart) {
        this.timestart = timestart;
    }

    public String getTimeend() {
        return timeend;
    }

    public void setTimeend(String timeend) {
        this.timeend = timeend;
    }

    public String getUserinfo() {
        return userinfo;
    }

    public void setUserinfo(String userinfo) {
        this.userinfo = userinfo;
    }

    public Boolean getUserphone() {
        return userphone;
    }

    public void setUserphone(Boolean userphone) {
        this.userphone = userphone;
    }

    public Long getCropsinfo() {
        return cropsinfo;
    }

    public void setCropsinfo(Long cropsinfo) {
        this.cropsinfo = cropsinfo;
    }

    public String getCropstime() {
        return cropstime;
    }

    public void setCropstime(String cropstime) {
        this.cropstime = cropstime;
    }

}
