package ps.emperor.easy_water.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IRRI_VALUE.
 */
public class IrriValue {

    private Long id;
    private String irriValue;
    private String userInfo;
    private String userPhone;
    private String cropName;
    private String cropStime;
    private String area;
    private String valueControlChanID;
    private String valueControlID;
    private String totalIrriTime;
    private String irriDuration;
    private String irriCount;
    private String irriWater;
    private String valueControlSwitch;
    private String isAllocationGrowers;
    private String isAllocationCrop;
    private String isAllocationGroup;
    private String groupName;

    public IrriValue() {
    }

    public IrriValue(Long id) {
        this.id = id;
    }

    public IrriValue(Long id, String irriValue, String userInfo, String userPhone, String cropName, String cropStime, String area, String valueControlChanID, String valueControlID, String totalIrriTime, String irriDuration, String irriCount, String irriWater, String valueControlSwitch, String isAllocationGrowers, String isAllocationCrop, String isAllocationGroup, String groupName) {
        this.id = id;
        this.irriValue = irriValue;
        this.userInfo = userInfo;
        this.userPhone = userPhone;
        this.cropName = cropName;
        this.cropStime = cropStime;
        this.area = area;
        this.valueControlChanID = valueControlChanID;
        this.valueControlID = valueControlID;
        this.totalIrriTime = totalIrriTime;
        this.irriDuration = irriDuration;
        this.irriCount = irriCount;
        this.irriWater = irriWater;
        this.valueControlSwitch = valueControlSwitch;
        this.isAllocationGrowers = isAllocationGrowers;
        this.isAllocationCrop = isAllocationCrop;
        this.isAllocationGroup = isAllocationGroup;
        this.groupName = groupName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIrriValue() {
        return irriValue;
    }

    public void setIrriValue(String irriValue) {
        this.irriValue = irriValue;
    }

    public String getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo;
    }

    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getCropName() {
        return cropName;
    }

    public void setCropName(String cropName) {
        this.cropName = cropName;
    }

    public String getCropStime() {
        return cropStime;
    }

    public void setCropStime(String cropStime) {
        this.cropStime = cropStime;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getValueControlChanID() {
        return valueControlChanID;
    }

    public void setValueControlChanID(String valueControlChanID) {
        this.valueControlChanID = valueControlChanID;
    }

    public String getValueControlID() {
        return valueControlID;
    }

    public void setValueControlID(String valueControlID) {
        this.valueControlID = valueControlID;
    }

    public String getTotalIrriTime() {
        return totalIrriTime;
    }

    public void setTotalIrriTime(String totalIrriTime) {
        this.totalIrriTime = totalIrriTime;
    }

    public String getIrriDuration() {
        return irriDuration;
    }

    public void setIrriDuration(String irriDuration) {
        this.irriDuration = irriDuration;
    }

    public String getIrriCount() {
        return irriCount;
    }

    public void setIrriCount(String irriCount) {
        this.irriCount = irriCount;
    }

    public String getIrriWater() {
        return irriWater;
    }

    public void setIrriWater(String irriWater) {
        this.irriWater = irriWater;
    }

    public String getValueControlSwitch() {
        return valueControlSwitch;
    }

    public void setValueControlSwitch(String valueControlSwitch) {
        this.valueControlSwitch = valueControlSwitch;
    }

    public String getIsAllocationGrowers() {
        return isAllocationGrowers;
    }

    public void setIsAllocationGrowers(String isAllocationGrowers) {
        this.isAllocationGrowers = isAllocationGrowers;
    }

    public String getIsAllocationCrop() {
        return isAllocationCrop;
    }

    public void setIsAllocationCrop(String isAllocationCrop) {
        this.isAllocationCrop = isAllocationCrop;
    }

    public String getIsAllocationGroup() {
        return isAllocationGroup;
    }

    public void setIsAllocationGroup(String isAllocationGroup) {
        this.isAllocationGroup = isAllocationGroup;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

}
