package ps.emperor.easy_water.greendao;
import android.database.Cursor;

import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table IRRIGATION_IS_FIRST.
*/
public class IrrigationIsFirstDao extends AbstractDao<IrrigationIsFirst, Long> {

    public static final String TABLENAME = "IRRIGATION_IS_FIRST";

    /**
     * Properties of entity IrrigationIsFirst.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Irrigation = new Property(1, String.class, "irrigation", false, "IRRIGATION");
        public final static Property IsFirst = new Property(2, Integer.class, "isFirst", false, "IS_FIRST");
    };


    public IrrigationIsFirstDao(DaoConfig config) {
        super(config);
    }
    
    public IrrigationIsFirstDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'IRRIGATION_IS_FIRST' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'IRRIGATION' TEXT," + // 1: irrigation
                "'IS_FIRST' INTEGER);"); // 2: isFirst
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'IRRIGATION_IS_FIRST'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, IrrigationIsFirst entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String irrigation = entity.getIrrigation();
        if (irrigation != null) {
            stmt.bindString(2, irrigation);
        }
 
        Integer isFirst = entity.getIsFirst();
        if (isFirst != null) {
            stmt.bindLong(3, isFirst);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public IrrigationIsFirst readEntity(Cursor cursor, int offset) {
        IrrigationIsFirst entity = new IrrigationIsFirst( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // irrigation
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // isFirst
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, IrrigationIsFirst entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIrrigation(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsFirst(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(IrrigationIsFirst entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(IrrigationIsFirst entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
