package ps.emperor.easy_water.greendao;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SINGLE_VALUE.
 */
public class SingleValue {

    private Long id;
    private String irrigation;
    private String valueID;
    private String valuestate;
    private String durationtime;

    public SingleValue() {
    }

    public SingleValue(Long id) {
        this.id = id;
    }

    public SingleValue(Long id, String irrigation, String valueID, String valuestate, String durationtime) {
        this.id = id;
        this.irrigation = irrigation;
        this.valueID = valueID;
        this.valuestate = valuestate;
        this.durationtime = durationtime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIrrigation() {
        return irrigation;
    }

    public void setIrrigation(String irrigation) {
        this.irrigation = irrigation;
    }

    public String getValueID() {
        return valueID;
    }

    public void setValueID(String valueID) {
        this.valueID = valueID;
    }

    public String getValuestate() {
        return valuestate;
    }

    public void setValuestate(String valuestate) {
        this.valuestate = valuestate;
    }

    public String getDurationtime() {
        return durationtime;
    }

    public void setDurationtime(String durationtime) {
        this.durationtime = durationtime;
    }

}
