package ps.emperor.easy_water.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WATER.
 */
public class Water {

    private Long id;
    private String water;
    private String isrelevance;

    public Water() {
    }

    public Water(Long id) {
        this.id = id;
    }

    public Water(Long id, String water, String isrelevance) {
        this.id = id;
        this.water = water;
        this.isrelevance = isrelevance;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWater() {
        return water;
    }

    public void setWater(String water) {
        this.water = water;
    }

    public String getIsrelevance() {
        return isrelevance;
    }

    public void setIsrelevance(String isrelevance) {
        this.isrelevance = isrelevance;
    }

}
